import Index from "./new";
import Head from "next/head";
import styles from "../styles/home.module.css";
import Edit from '../components/create_gallery/Edit'
import Preview from '../components/create_gallery/Preview'

export default function Create({ wallet }) {
  return (
    <>
      <Head>
        <title>Secret Collective - Virtual Gallery</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <Edit/>
      <Preview/>

      <style global jsx>{`
            body {
                overflow: hidden;
            }
        `}</style>

    </>

  );
}

export function getServerSideProps({ req, res }) {
  return { props: { wallet: req.cookies.wallet ?? null } };
}
